### ISSUE TITLE
wrong example

### ISSUE THREAD

**Issue by DarkPark** [waitingsong/node-myca-cli#2]
you have this example:

```bash
myca initcenter --name=ec --path="c:/users/<user>/.myca-ec"
```

but it fails with error:

```
length of pass must at least 4
```

**Comment by waitingsong** [comment]
will fix.
thanks

**Comment by waitingsong** [comment]
will fix after refactor of relative modules.
thanks

**Comment by waitingsong** [comment]
Which version you used ?
```bash
myca --version
# should output 0.2.3
```

It goes on without problem under both win7 and centos7:
```bash
myca initcenter --name=ec --path="c:/users/<user>/.myca-ec"
```

**Comment by DarkPark** [comment]
Ubuntu 18.04.1 LTS x86_64

**Comment by waitingsong** [comment]
I mean which myca-cli version 
```bash
myca --version
# should output 0.2.3
```

**Comment by DarkPark** [comment]
my output:

```
$ myca --version
0.2.3
```

**Comment by waitingsong** [comment]
pls try new myca-cli version v0.2.4:
```bash
npm i myca-cli@latest
// OR
npm i -g myca-cli@latest
```

**Comment by DarkPark** [comment]
still the same:

```
$ myca initca --name=ec
length of pass must at least 4
```

**Comment by waitingsong** [comment]
waiting distinguish

**Comment by DarkPark** [comment]
what do you mean?

**Comment by waitingsong** [comment]
I'll distinguish the issue. wait it.

**Comment by waitingsong** [comment]
try
```bash
npm i -g myca-cli@latest
```
then run:
```bash
myca --version
myca init -d
myca initcenter --name=ec --path="/tmp/myca-ec" -d
```

**Comment by DarkPark** [comment]
```
$ myca --version
2.0.0

$ myca init -d
{ cmd: 'init', options: null, needHelp: false, debug: true }
Default center created at path: "/home/dp/.myca"

$ myca initcenter --name=ec -d
/usr/lib/node_modules/myca-cli/dist/bin/myca-cli.js:234
        throw new Error('value of path empty')
        ^

Error: value of path empty
    at parseInitCenter (/usr/lib/node_modules/myca-cli/dist/bin/myca-cli.js:234:15)
    at parseOpts (/usr/lib/node_modules/myca-cli/dist/bin/myca-cli.js:166:16)
    at Object.<anonymous> (/usr/lib/node_modules/myca-cli/dist/bin/myca-cli.js:319:53)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by waitingsong** [comment]
param of path missing!
`myca initcenter --name=ec --path="/tmp/myca-ec" -d`

**Comment by DarkPark** [comment]
```
$ myca initcenter --name=ec --path="/home/dp/.myca" -d
{ cmd: 'initcenter',
  options: { name: 'ec', path: '/home/dp/.myca' },
  needHelp: false,
  debug: true }
{ name: 'ec', path: '/home/dp/.myca' }
{ name: 'ec', path: '/home/dp/.myca' }
center created with:
  centerName: "ec"
  path: "/home/dp/.myca"
```

But `myca init` has already created this directory. Why do you force me to enter it manually? I'm okay with the default dir.

**Comment by waitingsong** [comment]
In most cases we need not initcenter, except for multiple CA file such as one RSA and other EC, So i must create an individual folder containnin all necessary folders and copy of configure files.
It must specify unique path for each named center during calling initcenter() hence .

**Comment by waitingsong** [comment]
@DarkPark  try latest myca-cli , path of initcenter() can be ommited
```bash
myca initcenter --name=ec --path="/tmp/myca-ec" -d
// OR
myca initcenter --name=ecc -d
```

**Comment by DarkPark** [comment]
it works

```
$ myca initcenter --name=ec -d
{ cmd: 'initcenter',
  options: { name: 'ec', path: undefined },
  needHelp: false,
  debug: true }
{ name: 'ec', path: undefined }
center created with:
  centerName: "ec"
  path: "/home/dp/.myca-1548162251558"
```

though I would prefer `path: "/home/dp/.myca-ec"`

**Comment by waitingsong** [comment]
@DarkPark 
```bash
npm i -g myca-cli@latest
myca initcenter --name=foo -d
```
path suffix from center name

**Comment by DarkPark** [comment]
:+1:
